name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: opendistroforelasticsearch/security-maven:v1

    steps:

      - name: Checkout security-parent
        uses: actions/checkout@v1
        with:
          repository: opendistro-for-elasticsearch/security-parent
          ref: opendistro-0.9
      - name: Install security-parent
        run: mvn clean install -DskipTests --file ../security-parent/pom.xml

      - name: Checkout security-ssl
        uses: actions/checkout@v1

      - name: Test and install security-ssl
        run: mvn clean install

      - name: Checkout security
        uses: actions/checkout@v1
        with:
          repository: opendistro-for-elasticsearch/security
          ref: opendistro-0.9
      - name: Test and install security
        run: mvn clean install --file ../security/pom.xml

      - name: Checkout security-advanced-modules
        uses: actions/checkout@v1
        with:
          repository: opendistro-for-elasticsearch/security-advanced-modules
          ref: opendistro-0.9
      - name: Test and install security-advanced-modules
        run: mvn clean install --file ../security-advanced-modules/pom.xml

      - name: Build artifacts
        run: mvn clean package -Padvanced -DskipTests --file ../security/pom.xml

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: ../security/target/releases/
